## Evalue la expresión en los ejercicios 1 - 6 evalue la expresión

In [2]:
import numpy as np

arreglo_1 = np.array([[-5, 0], 
                      [3, -6]])

arreglo_2 = np.array([[7, 1],
                      [-2, -1]])

arreglo_3 = np.array([[-10, -8],
                      [14, 6]])

arreglo_result = arreglo_1 + arreglo_2 + arreglo_3

print(arreglo_result)



[[-8 -7]
 [15 -1]]


In [3]:

import numpy as np


arreglo_1 = np.array([[6, 8], 
                      [-1, 0]])

arreglo_2 = np.array([[0, 5],
                      [-3, -1]])

arreglo_3 = np.array([[-11, -7],
                      [2, -1]])

arreglo_result = arreglo_1 + arreglo_2 + arreglo_3

print(arreglo_result)





[[-5  6]
 [-2 -2]]


In [5]:


import numpy as np


arreglo_1 = np.array([[-4, 0, 1], 
                      [0, 2, 3]])

arreglo_2 = np.array([[2, 1, -2],
                      [3, -6, 0]])

arreglo_result = (arreglo_1 - arreglo_2) * 4

print(arreglo_result)




[[-24  -4  12]
 [-12  32  12]]


In [7]:

import numpy as np


arreglo_1 = np.array([5, -2, 4, 0])

arreglo_2 = np.array([14, 6, -18, 9])

arreglo_result = (arreglo_1 + arreglo_2) * 0.5

print(arreglo_result)


[ 9.5  2.  -7.   4.5]


In [8]:

import numpy as np

arreglo_1 = np.array([[0, -3], 
                      [7, 2]])

arreglo_2 = np.array([[-6, 3],
                      [8, 1]])

arreglo_3 = np.array([[4, -4],
                      [7, -9]])

arreglo_result = -3 * (arreglo_1 + arreglo_2) - 2 * arreglo_3

print(arreglo_result)

[[ 10   8]
 [-59   9]]


In [10]:

import numpy as np

arreglo_1 = np.array([[4, 11], 
                      [-2, -1],
                      [9, 3]])

arreglo_2 = np.array([[-5, -1],
                      [3, 4],
                      [0, 13]])

arreglo_3 = np.array([[7, 5],
                      [-9, -1],
                      [6, -1]])

arreglo_result = -1 * (arreglo_1) + (arreglo_2 + arreglo_3)/6

print(arreglo_result)


[[ -3.66666667 -10.33333333]
 [  1.           1.5       ]
 [ -8.          -1.        ]]


## Operaciones con matrices en los ejercicio 7 hasta el 12, realice las operaciones indicadas cuando a = 3, b = -4

In [11]:


import numpy as np


arreglo_1 = np.array([[4, 11], 
                      [-2, -1],
                      [9, 3]])

arreglo_2 = np.array([[-5, -1],
                      [3, 4],
                      [0, 13]])

arreglo_3 = np.array([[7, 5],
                      [-9, -1],
                      [6, -1]])

arreglo_result = -1 * (arreglo_1) + (arreglo_2 + arreglo_3)/6

print(arreglo_result)


[[ -3.66666667 -10.33333333]
 [  1.           1.5       ]
 [ -8.          -1.        ]]


In [19]:

import numpy as np

a = 3
b = 4

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 1],
              [-1, 2]])

O = np.array([[0, 0],
              [0, 0]])

# 7

arreglo_result = a * A + b * B

print("Ejercicio 7\n")
print(arreglo_result)

# 8

print("Ejercicio 8\n")

arreglo_result = A + B

print(arreglo_result)

# 9

print("Ejercicio 9\n")

arreglo_result = a * b * (B)

print(arreglo_result)

# 10

print("Ejercicio 10\n")

arreglo_result = (a + b) * B

print(arreglo_result)

# 11

print("Ejercicio 11\n")

arreglo_result = (a - b) * (A - B)

print(arreglo_result)

# 12

print("Ejercicio 12\n")

arreglo_result = (a * b) * O

print(arreglo_result)



Ejercicio 7

[[ 3 10]
 [ 5 20]]
Ejercicio 8

[[1 3]
 [2 6]]
Ejercicio 9

[[  0  12]
 [-12  24]]
Ejercicio 10

[[ 0  7]
 [-7 14]]
Ejercicio 11

[[-1 -1]
 [-4 -2]]
Ejercicio 12

[[0 0]
 [0 0]]


## Ejercicio del punto 13

In [25]:

import numpy as np

A = np.array([[-4, 0],
              [1, 5],
              [-3, 2]])

B = np.array([[1, 2],
              [-2, 1],
              [4, 4]])


# (a) 3X + 2A = B

X = (1/3) * (B - 2 * A)

print(f"El resultado es:\n {X}\n")

# (b) 2A - 5B = 3X

X = (2 * A - 5 * B) / 3

print(f"El resultado es:\n {X}\n")

# (c) X - 3A + 2B = 0

X = 3 * A - 2 * B

print(f"El resultado es:\n {X}\n")

# (d) 6X - 4A - 3B = 0

X = (4 * A + 3 * B) / 6

print(f"El resultado es:\n {X}\n")



El resultado es:
 [[ 3.          0.66666667]
 [-1.33333333 -3.        ]
 [ 3.33333333  0.        ]]

El resultado es:
 [[-4.33333333 -3.33333333]
 [ 4.          1.66666667]
 [-8.66666667 -5.33333333]]

El resultado es:
 [[-14  -4]
 [  7  13]
 [-17  -2]]

El resultado es:
 [[-2.16666667  1.        ]
 [-0.33333333  3.83333333]
 [ 0.          3.33333333]]



## Ejercicio del punto 14

In [61]:

import numpy as np

A = np.array([[-2, -1],
              [1, 0],
              [3, -4]])

B = np.array([[0, 3],
              [2, 0],
              [-4, -1]])


# (a) X = 3A - 2B

X = 3 * A - 2 * B

print(f"El resultado es:\n {X}\n")

# (b) 2X = 2A - B

X = (2 * A - B) / 2

print(f"El resultado es:\n {X}\n")

# (c) 2X + 3A = B

X = (B - 3 * A) / 2

print(f"El resultado es:\n {X}\n")

# (d) 2A + 4B = -2X

X = - (2 * A + 4 * B) / 2

print(f"El resultado es:\n {X}\n")


El resultado es:
 [[ -6  -9]
 [ -1   0]
 [ 17 -10]]

El resultado es:
 [[-2.  -2.5]
 [ 0.   0. ]
 [ 5.  -3.5]]

El resultado es:
 [[ 3.   3. ]
 [-0.5  0. ]
 [-6.5  5.5]]

El resultado es:
 [[ 2. -5.]
 [-5.  0.]
 [ 5.  6.]]



## Operaciones con matrices Ejercicios desde el punto 15 hasta el 20 siempre que c = 2

In Python, the `@` operator is used for matrix multiplication when working with numpy arrays. It performs a dot product operation between two matrices.

In your code, `B @ (C @ A)` is performing matrix multiplication in the order specified by the parentheses, i.e., it first multiplies matrix `C` with matrix `A`, and then multiplies the result with matrix `B`.

This is different from element-wise multiplication (`*`), which multiplies elements of the matrices at corresponding positions. The `@` operator is used when you want to perform actual matrix multiplication as defined in linear algebra.

In [41]:

import numpy as np

A = np.array([[1, 2, 3],
              [0, 1, -1]])

B = np.array([[1, 3],
              [-1, 2]])

C = np.array([[0, 1],
              [-1, 0]])

c = 2

# Ejercicio 15, B(C * A)

arreglo_result = B @ (C @ A)

print(f"El resultado es: \n {arreglo_result}\n")

# Ejercicio 16, C(B * C)

arreglo_result = C @ (B @ C)

print(f"El resultado es: \n {arreglo_result}\n")

# Ejercicio 17, (B + C)A

arreglo_result = (B + C) @ A

print(f"El resultado es: \n {arreglo_result}\n")

# Ejercicio 18, B(C + 0)

arreglo_result = B @ (C + 0)

print(f"El resultado es: \n {arreglo_result}\n")

#Ejercicio 19, (cB)(C + C)

arreglo_result = (c * B) @ (C + C)

print(f"El resultado es: \n {arreglo_result}\n")

#Ejercicio 20, B(cA)

arreglo_result = B @ (c * A)

print(f"El resultado es: \n {arreglo_result}\n")




El resultado es: 
 [[ -3  -5 -10]
 [ -2  -5  -5]]

El resultado es: 
 [[-2 -1]
 [ 3 -1]]

El resultado es: 
 [[ 1  6 -1]
 [-2 -2 -8]]

El resultado es: 
 [[-3  1]
 [-2 -1]]

El resultado es: 
 [[-12   4]
 [ -8  -4]]

El resultado es: 
 [[  2  10   0]
 [ -2   0 -10]]



## Asociatividad de la multiplicación de matrices Ejercicios 21 y 22

In [50]:

import numpy as np

# Matrices para del punto 21

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 1],
              [2, 3]])

C = np.array([[3, 0],
              [0, 1]])

print("Se obtiene el mismo resultado en ambos casos\n")


print("Resultados del punto 22\n")

# Ejercicio 21, primera agrupación (AB)C

arreglo_result = (A @ B) @ C

print(f"El resultado es: \n {arreglo_result}\n")

# Ejercicio 21, segunda agrupación A(BC)

arreglo_result = A @ (B @ C)

print(f"El resultado es: \n {arreglo_result}\n")



# Matrices para del punto 22

A = np.array([[-4, 2],
              [1, -3]])

B = np.array([[1, -5, 0],
              [-2, 3, 3]])

C = np.array([[-3, 4],
              [0, 1],
              [-1, 1]])	

print("Resultados del punto 22\n")

# Ejercicio 22, primera agrupación (AB)C

arreglo_result = (A @ B) @ C

print(f"El resultado es: \n {arreglo_result}\n")

# Ejercicio 22, segunda agrupación A(BC)

arreglo_result = A @ (B @ C)

print(f"El resultado es: \n {arreglo_result}\n")


Se obtiene el mismo resultado en ambos casos

Resultados del punto 22

El resultado es: 
 [[12  7]
 [24 15]]

El resultado es: 
 [[12  7]
 [24 15]]

Resultados del punto 22

El resultado es: 
 [[ 18   0]
 [-12   5]]

El resultado es: 
 [[ 18   0]
 [-12   5]]



## No conmutativa de multiplicación de matrices Ejercicios 23 y 24

In [54]:
from fractions import Fraction
import numpy as np


# Matrices para del punto 23

A = np.array([[-2, 1],
              [0, -3]])

B = np.array([[4, 0],
              [-1, 2]])

# Mensaje Resultado

print("Resultados del punto, como se puede ver no son iguales\n")

print("Resultados del punto 23\n")

# Ejercicio 23, primera agrupación AB

arreglo_result = A @ B

print(f"El resultado de AB es: \n {arreglo_result}\n")

# Ejercicio 23, segunda agrupación BA

arreglo_result = B @ A

print(f"El resultado de BA es: \n {arreglo_result}\n")


# Matrices para del punto 24

A = np.array([[Fraction(1, 4), Fraction(1, 2)],
              [Fraction(1, 2), Fraction(1, 2)]])


B = np.array([[Fraction(1, 2), Fraction(1, 2)],
              [Fraction(1, 2), Fraction(1, 4)]])

print("Resultados del punto 24\n")

# Ejercicios 24, primera agrupación AB

arreglo_result = A @ B
arreglo_result_convert = np.float64(arreglo_result)

print(f"El resultado de AB es: \n {arreglo_result_convert}\n")

# Ejercicios 24, segunda agrupación BA

arreglo_result = B @ A
arreglo_result_convert = np.float64(arreglo_result)

print(f"El resultado de BA es: \n {arreglo_result_convert}\n")




Resultados del punto, como se puede ver no son iguales

Resultados del punto 23

El resultado de AB es: 
 [[-9  2]
 [ 3 -6]]

El resultado de BA es: 
 [[-8  4]
 [ 2 -7]]

Resultados del punto 24

El resultado de AB es: 
 [[0.375 0.25 ]
 [0.5   0.375]]

El resultado de BA es: 
 [[0.375 0.5  ]
 [0.25  0.375]]



## Productos de matrices iguales Ejercicios 25 y 26

In [57]:

import numpy as np


# Matrices para del punto 25

A = np.array([[0, 1],
              [0, 1]])

B = np.array([[1, 0],
              [1, 0]])

C = np.array([[2, 3],
              [3, 3]])

# Ejercicios 25, agrupaciones AC = BC

arreglo_result = A @ C

print(f"El resultado de BA es: \n {arreglo_result}\n")

arreglo_result = B @ C

print(f"El resultado de BC es: \n {arreglo_result}\n")

print("Como se puede ver los resultados son iguales incluso cuando A != B\n")

# Matrices para del punto 26

A = np.array([[1, 2, 3],
              [0, 5, 4],
              [3, -2, 1]])

B = np.array([[4, -6, 3],
              [5, 4, 4],
              [-1, 0, 1]])

C = np.array([[0, 0, 0],
              [0, 0, 0],
              [4, -2, 3]])


# Ejercicios 26, agrupaciones AC = BC

arreglo_result = A @ C

print(f"El resultado de BA es: \n {arreglo_result}\n")

arreglo_result = B @ C

print(f"El resultado de BC es: \n {arreglo_result}\n")


El resultado de BA es: 
 [[3 3]
 [3 3]]

El resultado de BC es: 
 [[2 3]
 [2 3]]

Como se puede ver los resultados son iguales incluso cuando A != B

El resultado de BA es: 
 [[12 -6  9]
 [16 -8 12]
 [ 4 -2  3]]

El resultado de BC es: 
 [[12 -6  9]
 [16 -8 12]
 [ 4 -2  3]]



## Producto de matriz cero Ejercicios 27 y 28

In [59]:

import numpy as np


# Matrices para del punto 27

A = np.array([[3, 3],
              [4, 4]])

B = np.array([[1, -1],
              [-1, 1]])

# Ejercicios 27, agrupación AB = 0

arreglo_result = A @ B

print(f"El resultado de AB es: \n {arreglo_result}\n")


# Matrices para del punto 28

A = np.array([[2, 4],
              [2, 4]])

B = np.array([[1, -2],
              [Fraction(-1, 2), 1]])


# Ejercicios 27, agrupación AB = 0

arreglo_result = A @ B
arreglo_result_convert = np.float64(arreglo_result)

print(f"El resultado de AB es: \n {arreglo_result_convert}\n")

El resultado de AB es: 
 [[0 0]
 [0 0]]

El resultado de AB es: 
 [[0. 0.]
 [0. 0.]]

